import LanglandsOracles.Pseudocharacter

/-!
# Generation certificates in GL₂(ℤ/n): breadth-first multiplicative closure on machine naturals.

Matrices over ℤ/n are encoded as base-n indices i < n⁴, closures keep the set of seen elements as
a bitmask, and every step is a GMP operation in the kernel.  `generatedIdx_sub` proves soundness:
each index whose bit is set decodes to a product of the generators, so a kernel evaluation
"`generatedIdx gens` has every bit of GL₂ set" certifies that any multiplicatively closed subset
containing the generators is all of GL₂(ℤ/n).  `mem_gl`: the enumeration `gl n` is complete.
-/
namespace Oracles

namespace Mat2

/-- Elements enumerated by `gl n` are exactly the matrices with nonzero determinant. -/
theorem mem_fins {n : Nat} (a : Fin n) : a ∈ fins n := by
  unfold fins
  rw [List.mem_filterMap]
  exact ⟨a.val, List.mem_range.mpr a.isLt, by simp [a.isLt]⟩

theorem mem_all {n : Nat} (x : Mat2 n) : x ∈ all n := by
  unfold all
  simp only [List.mem_flatMap, List.mem_map]
  exact ⟨x.a, mem_fins _, x.b, mem_fins _, x.c, mem_fins _, x.d, mem_fins _, rfl⟩

theorem mem_gl {n : Nat} (x : Mat2 n) (hx : x.det.val ≠ 0) : x ∈ gl n := by
  unfold gl
  rw [List.mem_filter]
  exact ⟨mem_all x, bne_iff_ne.mpr hx⟩

variable {n : Nat} [NeZero n]

/-- Matrices as indices 0 ≤ i < n⁴ (base n), so that closures run on machine naturals in the kernel. -/
def finN (k : Nat) : Fin n := ⟨k % n, Nat.mod_lt k (Nat.pos_of_neZero n)⟩
def encode (x : Mat2 n) : Nat := x.a.val + n * (x.b.val + n * (x.c.val + n * x.d.val))
def decode (n : Nat) [NeZero n] (i : Nat) : Mat2 n := ⟨finN i, finN (i / n), finN (i / n / n), finN (i / n / n / n)⟩
def mulIdx (n : Nat) [NeZero n] (i j : Nat) : Nat := encode (M2.mul (decode n i) (decode n j))

theorem decode_encode (x : Mat2 n) : decode n (encode x) = x := by
  obtain ⟨⟨a, ha⟩, ⟨b, hb⟩, ⟨c, hc⟩, ⟨d, hd⟩⟩ := x
  have h1 : ∀ u k : Nat, u < n → (u + n * k) % n = u := fun u k hu => by
    rw [Nat.add_mul_mod_self_left, Nat.mod_eq_of_lt hu]
  have h2 : ∀ u k : Nat, u < n → (u + n * k) / n = k := fun u k hu => by
    rw [Nat.add_mul_div_left _ _ (Nat.pos_of_neZero n), Nat.div_eq_of_lt hu, Nat.zero_add]
  simp only [decode, encode, finN, M2.mk.injEq, Fin.mk.injEq]
  rw [h1 a _ ha, h2 a _ ha, h1 b _ hb, h2 b _ hb, h1 c _ hc, h2 c _ hc, Nat.mod_eq_of_lt hd]
  exact ⟨rfl, rfl, rfl, rfl⟩

/-- Bitmask of a list of indices. -/
def mask (m : Nat) (l : List Nat) : Nat := l.foldl (fun m j => m ||| 2 ^ j) m

theorem testBit_mask {m : Nat} {l : List Nat} {i : Nat} (h : (mask m l).testBit i = true) :
    m.testBit i = true ∨ i ∈ l := by
  induction l generalizing m with
  | nil => exact Or.inl h
  | cons j l ih =>
    rcases ih h with h' | h'
    · rw [Nat.testBit_or] at h'
      rcases Bool.or_eq_true _ _ |>.mp h' with h'' | h''
      · exact Or.inl h''
      · rw [Nat.testBit_two_pow] at h''
        exact Or.inr (List.mem_cons.mpr (Or.inl (of_decide_eq_true h'').symm))
    · exact Or.inr (List.mem_cons_of_mem _ h')

/-- Products of the frontier with the generators that are not yet seen. -/
def stepIdx (n : Nat) [NeZero n] (gens : List Nat) (seen : Nat) (frontier : List Nat) : List Nat :=
  (frontier.flatMap fun i => gens.map fun g => mulIdx n i g).filter fun j => !seen.testBit j

/-- Breadth-first multiplicative closure, with fuel; `seen` is a bitmask. -/
def closureIdx (n : Nat) [NeZero n] (gens : List Nat) : Nat → Nat → List Nat → Nat
  | 0, seen, _ => seen
  | k + 1, seen, frontier =>
    match stepIdx n gens seen frontier with
    | [] => seen
    | y :: ys => closureIdx n gens k (mask seen (y :: ys)) (y :: ys)

/-- The semigroup generated by a list (its closure under multiplication; in a finite group, the subgroup). -/
def generatedIdx (n : Nat) [NeZero n] (gens : List Nat) : Nat := closureIdx n gens (n ^ 4) (mask 0 gens) gens

section soundness

variable (H : List (Mat2 n)) (hmul : ∀ x ∈ H, ∀ y ∈ H, M2.mul x y ∈ H)
include hmul

theorem stepIdx_sub (gens : List Nat) (seen : Nat) (frontier : List Nat)
    (hg : ∀ g ∈ gens, decode n g ∈ H) (hf : ∀ i ∈ frontier, decode n i ∈ H) :
    ∀ j ∈ stepIdx n gens seen frontier, decode n j ∈ H := by
  intro j hj
  unfold stepIdx at hj
  obtain ⟨i, hi, hj'⟩ := List.mem_flatMap.mp (List.mem_filter.mp hj).1
  obtain ⟨g, hg', rfl⟩ := List.mem_map.mp hj'
  unfold mulIdx
  rw [decode_encode]
  exact hmul _ (hf i hi) _ (hg g hg')

theorem closureIdx_sub (gens : List Nat) (hg : ∀ g ∈ gens, decode n g ∈ H) :
    ∀ (k seen : Nat) (frontier : List Nat), (∀ i, seen.testBit i = true → decode n i ∈ H) →
      (∀ i ∈ frontier, decode n i ∈ H) → ∀ i, (closureIdx n gens k seen frontier).testBit i = true → decode n i ∈ H
  | 0, _, _, hs, _ => hs
  | k + 1, seen, frontier, hs, hf => by
    have hnew := stepIdx_sub H hmul gens seen frontier hg hf
    unfold closureIdx
    split
    · exact hs
    · next y ys heq =>
      rw [heq] at hnew
      exact closureIdx_sub gens hg k _ _
        (fun i hi => (testBit_mask hi).elim (hs i) (hnew i)) hnew

theorem generatedIdx_sub (gens : List Nat) (hg : ∀ g ∈ gens, decode n g ∈ H) :
    ∀ i, (generatedIdx n gens).testBit i = true → decode n i ∈ H :=
  closureIdx_sub H hmul gens hg (n ^ 4) _ gens
    (fun i hi => (testBit_mask hi).elim (fun h => by rw [Nat.zero_testBit] at h; exact absurd h Bool.false_ne_true) (hg i)) hg

end soundness

end Mat2

end Oracles

namespace Oracles.Mat2

/-- The generic generation certificate: if every (P, Q)-pair generates GL₂(ℤ/n) (a kernel fact
`hpairs`), then any multiplicatively closed subset containing a P-element and a Q-element is all of
GL₂(ℤ/n). -/
theorem generated_of_pairs (n : Nat) [NeZero n] (P Q : Mat2 n → Bool)
    (hP : ∀ g, P g = true → g ∈ gl n) (hQ : ∀ h, Q h = true → h ∈ gl n)
    (hpairs : ((gl n).filter P).all (fun g => ((gl n).filter Q).all fun h =>
      (gl n).all fun x => (generatedIdx n [encode g, encode h]).testBit (encode x)) = true)
    (H : List (Mat2 n)) (hmul : ∀ x ∈ H, ∀ y ∈ H, M2.mul x y ∈ H)
    {g h : Mat2 n} (hg : g ∈ H) (hh : h ∈ H) (hPg : P g = true) (hQh : Q h = true) :
    ∀ x ∈ gl n, x ∈ H := by
  intro x hx
  have hg' : g ∈ (gl n).filter P := List.mem_filter.mpr ⟨hP g hPg, hPg⟩
  have hh' : h ∈ (gl n).filter Q := List.mem_filter.mpr ⟨hQ h hQh, hQh⟩
  have hx' := List.all_eq_true.mp (List.all_eq_true.mp (List.all_eq_true.mp hpairs g hg') h hh') x hx
  have hgens : ∀ i ∈ [encode g, encode h], decode n i ∈ H := by
    intro i hi
    rcases List.mem_cons.mp hi with rfl | hi
    · rw [decode_encode]; exact hg
    rcases List.mem_cons.mp hi with rfl | hi
    · rw [decode_encode]; exact hh
    exact absurd hi List.not_mem_nil
  have := generatedIdx_sub H hmul _ hgens _ hx'
  rwa [decode_encode] at this

end Oracles.Mat2
