import LanglandsOracles.Pseudocharacter

/-!
# Generation certificates in GL₂(ℤ/n): breadth-first multiplicative closure on machine naturals.

Matrices over ℤ/n are encoded as base-n indices i < n⁴, closures keep the set of seen elements as
a bitmask, and every step is a GMP operation in the kernel.  `generatedIdx_sub` proves soundness:
each index whose bit is set decodes to a product of the generators, so a kernel evaluation
"`generatedIdx gens` has every bit of GL₂ set" certifies that any multiplicatively closed subset
containing the generators is all of GL₂(ℤ/n).  `mem_gl`: the enumeration `gl n` is complete.
-/
namespace Oracles

namespace Mat2

/-- Elements enumerated by `gl n` are exactly the matrices with nonzero determinant. -/
theorem mem_fins {n : Nat} (a : Fin n) : a ∈ fins n := by
  unfold fins
  rw [List.mem_filterMap]
  exact ⟨a.val, List.mem_range.mpr a.isLt, by simp [a.isLt]⟩

theorem mem_all {n : Nat} (x : Mat2 n) : x ∈ all n := by
  unfold all
  simp only [List.mem_flatMap, List.mem_map]
  exact ⟨x.a, mem_fins _, x.b, mem_fins _, x.c, mem_fins _, x.d, mem_fins _, rfl⟩

theorem mem_gl {n : Nat} (x : Mat2 n) (hx : x.det.val ≠ 0) : x ∈ gl n := by
  unfold gl
  rw [List.mem_filter]
  exact ⟨mem_all x, bne_iff_ne.mpr hx⟩

variable {n : Nat} [NeZero n]

/-- Matrices as indices 0 ≤ i < n⁴ (base n), so that closures run on machine naturals in the kernel. -/
def finN (k : Nat) : Fin n := ⟨k % n, Nat.mod_lt k (Nat.pos_of_neZero n)⟩
def encode (x : Mat2 n) : Nat := x.a.val + n * (x.b.val + n * (x.c.val + n * x.d.val))
def decode (n : Nat) [NeZero n] (i : Nat) : Mat2 n := ⟨finN i, finN (i / n), finN (i / n / n), finN (i / n / n / n)⟩
def mulIdx (n : Nat) [NeZero n] (i j : Nat) : Nat := encode (M2.mul (decode n i) (decode n j))

theorem decode_encode (x : Mat2 n) : decode n (encode x) = x := by
  obtain ⟨⟨a, ha⟩, ⟨b, hb⟩, ⟨c, hc⟩, ⟨d, hd⟩⟩ := x
  have h1 : ∀ u k : Nat, u < n → (u + n * k) % n = u := fun u k hu => by
    rw [Nat.add_mul_mod_self_left, Nat.mod_eq_of_lt hu]
  have h2 : ∀ u k : Nat, u < n → (u + n * k) / n = k := fun u k hu => by
    rw [Nat.add_mul_div_left _ _ (Nat.pos_of_neZero n), Nat.div_eq_of_lt hu, Nat.zero_add]
  simp only [decode, encode, finN, M2.mk.injEq, Fin.mk.injEq]
  rw [h1 a _ ha, h2 a _ ha, h1 b _ hb, h2 b _ hb, h1 c _ hc, h2 c _ hc, Nat.mod_eq_of_lt hd]
  exact ⟨rfl, rfl, rfl, rfl⟩

omit [NeZero n] in
theorem encode_lt (x : Mat2 n) : encode x < n ^ 4 := by
  obtain ⟨⟨a, ha⟩, ⟨b, hb⟩, ⟨c, hc⟩, ⟨d, hd⟩⟩ := x
  have step : ∀ u k m : Nat, u < n → k < m → u + n * k < n * m := fun u k m hu hk =>
    calc u + n * k < n + n * k := Nat.add_lt_add_right hu _
      _ = n * (k + 1) := by rw [Nat.mul_succ, Nat.add_comm]
      _ ≤ n * m := Nat.mul_le_mul_left n hk
  have e : n ^ 4 = n * (n * (n * n)) := by
    show (((1 * n) * n) * n) * n = n * (n * (n * n))
    rw [Nat.one_mul]
    ac_rfl
  show a + n * (b + n * (c + n * d)) < n ^ 4
  rw [e]
  exact step a _ _ ha (step b _ _ hb (step c d n hc hd))

theorem encode_inj {g h : Mat2 n} (e : encode g = encode h) : g = h := by
  have := congrArg (decode n) e
  rwa [decode_encode, decode_encode] at this

/-- Bitmask of a list of indices. -/
def mask (m : Nat) (l : List Nat) : Nat := l.foldl (fun m j => m ||| 2 ^ j) m

theorem testBit_mask {m : Nat} {l : List Nat} {i : Nat} (h : (mask m l).testBit i = true) :
    m.testBit i = true ∨ i ∈ l := by
  induction l generalizing m with
  | nil => exact Or.inl h
  | cons j l ih =>
    rcases ih h with h' | h'
    · rw [Nat.testBit_or] at h'
      rcases Bool.or_eq_true _ _ |>.mp h' with h'' | h''
      · exact Or.inl h''
      · rw [Nat.testBit_two_pow] at h''
        exact Or.inr (List.mem_cons.mpr (Or.inl (of_decide_eq_true h'').symm))
    · exact Or.inr (List.mem_cons_of_mem _ h')

/-- Products of the frontier with the generators that are not yet seen, through a multiplication
oracle `m i g` (the encoded product of the element with index i and the generator g). -/
def stepIdx (m : Nat → Nat → Nat) (gens : List Nat) (seen : Nat) (frontier : List Nat) : List Nat :=
  (frontier.flatMap fun i => gens.map fun g => m i g).filter fun j => !seen.testBit j

/-- Breadth-first multiplicative closure, with fuel; `seen` is a bitmask. -/
def closureIdx (m : Nat → Nat → Nat) (gens : List Nat) : Nat → Nat → List Nat → Nat
  | 0, seen, _ => seen
  | k + 1, seen, frontier =>
    match stepIdx m gens seen frontier with
    | [] => seen
    | y :: ys => closureIdx m gens k (mask seen (y :: ys)) (y :: ys)

/-- The semigroup generated by a list of encoded matrices (its closure under multiplication; in a
finite group, the subgroup). -/
def generatedIdx (n : Nat) [NeZero n] (gens : List Nat) : Nat :=
  closureIdx (mulIdx n) gens (n ^ 4) (mask 0 gens) gens

section soundness

variable (H : List (Mat2 n)) (m : Nat → Nat → Nat) (gens : List Nat)
-- the oracle sends (the code of) an element of H and a generator to the code of an element of H
variable (hm : ∀ x ∈ H, ∀ g ∈ gens, ∃ y ∈ H, m (encode x) g = encode y)
include hm

/-- Every index produced is the code of an element of H: the invariant of the closure. -/
def Codes (H : List (Mat2 n)) (i : Nat) : Prop := ∃ x ∈ H, i = encode x

omit [NeZero n] in
theorem stepIdx_sub (seen : Nat) (frontier : List Nat) (hf : ∀ i ∈ frontier, Codes H i) :
    ∀ j ∈ stepIdx m gens seen frontier, Codes H j := by
  intro j hj
  unfold stepIdx at hj
  obtain ⟨i, hi, hj'⟩ := List.mem_flatMap.mp (List.mem_filter.mp hj).1
  obtain ⟨g, hg', rfl⟩ := List.mem_map.mp hj'
  obtain ⟨x, hx, rfl⟩ := hf i hi
  obtain ⟨y, hy, e⟩ := hm x hx g hg'
  exact ⟨y, hy, e⟩

omit [NeZero n] in
theorem closureIdx_sub :
    ∀ (k seen : Nat) (frontier : List Nat), (∀ i, seen.testBit i = true → Codes H i) →
      (∀ i ∈ frontier, Codes H i) → ∀ i, (closureIdx m gens k seen frontier).testBit i = true → Codes H i
  | 0, _, _, hs, _ => hs
  | k + 1, seen, frontier, hs, hf => by
    have hnew := stepIdx_sub H m gens hm seen frontier hf
    unfold closureIdx
    split
    · exact hs
    · next y ys heq =>
      rw [heq] at hnew
      exact closureIdx_sub k _ _ (fun i hi => (testBit_mask hi).elim (hs i) (hnew i)) hnew

/-- Starting from codes of elements of H, every bit set by the closure is the code of an element of H. -/
theorem closureIdx_mem (init : List Nat) (hinit : ∀ i ∈ init, Codes H i) (k : Nat) :
    ∀ x : Mat2 n, (closureIdx m gens k (mask 0 init) init).testBit (encode x) = true → x ∈ H := by
  intro x hx
  obtain ⟨y, hy, e⟩ := closureIdx_sub H m gens hm k _ init
    (fun i hi => (testBit_mask hi).elim
      (fun h => by rw [Nat.zero_testBit] at h; exact absurd h Bool.false_ne_true) (hinit i)) hinit _ hx
  rw [encode_inj e]
  exact hy

end soundness

/-- The generic generation certificate: if every (P, Q)-pair generates GL₂(ℤ/n) (a kernel fact
`hpairs`, closures through `mulIdx`), then any multiplicatively closed subset containing a P-element
and a Q-element is all of GL₂(ℤ/n). -/
theorem generated_of_pairs (n : Nat) [NeZero n] (P Q : Mat2 n → Bool)
    (hP : ∀ g, P g = true → g ∈ gl n) (hQ : ∀ h, Q h = true → h ∈ gl n)
    (hpairs : ((gl n).filter P).all (fun g => ((gl n).filter Q).all fun h =>
      (gl n).all fun x => (generatedIdx n [encode g, encode h]).testBit (encode x)) = true)
    (H : List (Mat2 n)) (hmul : ∀ x ∈ H, ∀ y ∈ H, M2.mul x y ∈ H)
    {g h : Mat2 n} (hg : g ∈ H) (hh : h ∈ H) (hPg : P g = true) (hQh : Q h = true) :
    ∀ x ∈ gl n, x ∈ H := by
  intro x hx
  have hg' : g ∈ (gl n).filter P := List.mem_filter.mpr ⟨hP g hPg, hPg⟩
  have hh' : h ∈ (gl n).filter Q := List.mem_filter.mpr ⟨hQ h hQh, hQh⟩
  have hx' := List.all_eq_true.mp (List.all_eq_true.mp (List.all_eq_true.mp hpairs g hg') h hh') x hx
  have hgens : ∀ i ∈ [encode g, encode h], Codes H i := by
    intro i hi
    rcases List.mem_cons.mp hi with rfl | hi
    · exact ⟨g, hg, rfl⟩
    rcases List.mem_cons.mp hi with rfl | hi
    · exact ⟨h, hh, rfl⟩
    exact absurd hi List.not_mem_nil
  have hm : ∀ y ∈ H, ∀ i ∈ [encode g, encode h], ∃ z ∈ H, mulIdx n (encode y) i = encode z := by
    intro y hy i hi
    obtain ⟨w, hw, rfl⟩ := hgens i hi
    exact ⟨M2.mul y w, hmul y hy w hw, by simp only [mulIdx, decode_encode]⟩
  exact closureIdx_mem H (mulIdx n) _ hm _ hgens _ x hx'

end Mat2

end Oracles
