import LanglandsOracles
open Oracles
#print axioms ExcursionData.ofHom
#print axioms hecke_eq_character
#print axioms lrInvariant_tilde
#print axioms procesi_GL2_F3
#print axioms mod3_excursion_37a1
#print axioms brandt_eigenvector_37a1
#print axioms brandt_certificates
#print axioms lseries_certificates
#print axioms function_field_l_functions
#print axioms eichler_selberg_tau
#print axioms ExcursionData.map_one
#print axioms frobenius_matrices_mod3_37a1
#print axioms eichler_selberg_level_N
#print axioms isogeny_graphs_recomputed
#print axioms gl1_character
#print axioms gl1_character_one
#print axioms gl2_pseudocharacter
#print axioms exChar_comm
#print axioms M2.procesi
#print axioms gl2_ring_pseudocharacter
#print axioms gl2_Zmod_pseudocharacter
#print axioms gl2_Fp_pseudocharacter
#print axioms Mat2.generated_by_ord8_unip
#print axioms mod3_image_37a1_full
#print axioms Mat2.generated_by_ord3_ord2
#print axioms Mat2.image_C2
#print axioms mod2_image_S3
#print axioms mod2_image_C2
#print axioms Mat2.Tprime_procesi
#print axioms Mat2.rep_certified
#print axioms Mat2.bad_not_realised
#print axioms Mat2.rep_unique
#print axioms Mat2.mulNat_eq
#print axioms Mat2.pair_sound
#print axioms Mat2.data_sound
#print axioms mod5_images_full
#print axioms mod7_images_full
#print axioms mod11_images_full
#print axioms mod13_images_full
#print axioms mod17_images_full
#print axioms mod19_images_full
#print axioms mod23_images_full
#print axioms Satake.sphere_eq_sat
#print axioms Satake.sat_weyl
#print axioms Satake.sat_hecke
#print axioms Satake.sat_hecke_one
#print axioms Satake.sat_eq_chi_sub
#print axioms Satake.chi_clebsch_gordan
#print axioms Satake.ball_eq_chi
#print axioms Satake.invariant_decomposes
#print axioms Satake.hecke_seq_eq_h
#print axioms Satake.power_sum_eq
#print axioms Biext.ordO_odd_iff
#print axioms Biext.deligne_uniform
#print axioms Biext.generic_eq_du
#print axioms Biext.exchange_strict
#print axioms Biext.twist_symm
#print axioms Biext.twist_cocycle
#print axioms Biext.twist_rigid_left
#print axioms Biext.twist_rigid_base
#print axioms Biext.no_frame_fix
