import LanglandsOracles
open Oracles
#print axioms ExcursionData.ofHom
#print axioms hecke_eq_character
#print axioms lrInvariant_tilde
#print axioms procesi_GL2_F3
#print axioms mod3_excursion_37a1
#print axioms brandt_eigenvector_37a1
#print axioms brandt_certificates
#print axioms lseries_certificates
#print axioms function_field_l_functions
#print axioms eichler_selberg_tau
#print axioms ExcursionData.map_one
#print axioms frobenius_matrices_mod3_37a1
#print axioms eichler_selberg_level_N
#print axioms isogeny_graphs_recomputed
#print axioms gl1_character
#print axioms gl1_character_one
#print axioms gl2_pseudocharacter
#print axioms exChar_comm
#print axioms M2.procesi
#print axioms gl2_ring_pseudocharacter
#print axioms gl2_Zmod_pseudocharacter
#print axioms gl2_Fp_pseudocharacter
#print axioms Mat2.generated_by_ord8_unip
#print axioms mod3_image_37a1_full
#print axioms Mat2.generated_by_ord3_ord2
#print axioms Mat2.image_C2
#print axioms mod2_image_S3
#print axioms mod2_image_C2
#print axioms Mat2.Tprime_procesi
#print axioms Mat2.rep_certified
#print axioms Mat2.bad_not_realised
#print axioms Mat2.rep_unique
#print axioms Mat2.mulNat_eq
#print axioms Mat2.pair_sound
#print axioms Mat2.data_sound
#print axioms mod5_images_full
#print axioms mod7_images_full
#print axioms mod11_images_full
