import LanglandsOracles.QForms
import LanglandsOracles.TraceFormula
import LanglandsOracles.Matrix
import LanglandsOracles.Carlitz
import LanglandsOracles.Certificates
import LanglandsOracles.Data
import LanglandsOracles.BrandtCertificates
import LanglandsOracles.LSeriesCertificates
