"""Export exact Python-side data as Lean literals: lean/LanglandsOracles/Data.lean.

Lean re-derives the arithmetic side (class numbers, Eichler's formula, zeta) and certifies
the exported spectral data (Brandt matrices, L-series coefficient vectors) against it.
Deterministic: the test suite regenerates the file and requires it to be unchanged.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from langlands.brandt import SupersingularLocus  # noqa: E402
from langlands.gl1 import all_characters, closed_points, l_series  # noqa: E402
from langlands.newforms import newforms_of_level  # noqa: E402
from langlands.ec_function_field import FunctionFieldCurve, monic_irreducibles  # noqa: E402

BRANDT_PRIMES = (11, 13, 17, 19, 23, 29, 31, 37)
BRANDT_ELLS = (2, 3, 5, 7)
GL1_PRIMES = (5, 7)


def lean_list(xs) -> str:
    return "[" + ", ".join(str(x) for x in xs) + "]"


def lean_matrix(M) -> str:
    return "[" + ", ".join(lean_list(M.row(i)) for i in range(M.rows)) + "]"


def brandt_block() -> list[str]:
    out = ["/-- (p, |Aut E_i|, [(ell, B(ell))]) for supersingular loci; B(2), B(3) by Phi_ell, B(5), B(7) by Vélu. -/",
           "def brandtData : List (Nat × List Nat × List (Nat × IMat)) := ["]
    for p in BRANDT_PRIMES:
        L = SupersingularLocus.of(p)
        mats = ", ".join(f"({ell}, {lean_matrix(L.brandt_matrix(ell))})" for ell in BRANDT_ELLS if ell != p)
        out.append(f"  ({p}, {lean_list(L.aut_orders)}, [{mats}]),")
    out[-1] = out[-1].rstrip(",")
    out.append("]")
    return out


def gl1_block() -> list[str]:
    E37 = newforms_of_level(37)[0]
    out = ["/-- (p, a_p, N, [(trivial?, coefficients c_0..c_D of L(chi, T) in Z[Z/N])]) for 37a1 mod p. -/",
           "def lSeriesData : List (Nat × Int × Nat × List (Bool × List (List Int))) := ["]
    for p in GL1_PRIMES:
        E = E37.reduction(p)
        order = 4 if p == 5 else 3
        pts = closed_points(E, order)
        chars = []
        for chi in all_characters(E.structure):
            L = l_series(E, chi, order, pts)
            chars.append(f"({'true' if chi.is_trivial else 'false'}, {lean_list(lean_list(c) for c in L)})")
        out.append(f"  ({p}, {E.trace_of_frobenius}, {E.structure.exponent}, [{', '.join(chars)}]),")
    out[-1] = out[-1].rstrip(",")
    out.append("]")
    return out


FUNCTION_FIELD_CURVES = (
    ("E_t3", FunctionFieldCurve(2, ((0, 1), (), (), (1,), ())), 5),
    ("E_t4", FunctionFieldCurve(2, ((0, 1), (), (0, 0, 1), (1,), (0, 1, 1, 1))), 5),
    ("E3_A", FunctionFieldCurve(3, ((), (0, 0, 1), (), (0, 1), (1,))), 4),
    ("E3_B", FunctionFieldCurve(3, ((), (0, 0, 1), (), (0, 2), (1,))), 4),
)


def function_field_block() -> list[str]:
    """(q, order, [(degree, kind, a)]) per curve: kind 0 good, 1 multiplicative, 2 additive (oo included)."""
    kinds = {"good": 0, "split": 1, "nonsplit": 1, "additive": 2}
    out = ["/-- Local data of elliptic curves over F_q(t): (q, order, [(deg v, kind, a_v)]) for all places of degree <= order. -/",
           "def functionFieldLocalData : List (Nat × Nat × List (Nat × Nat × Int)) := ["]
    for _, E, order in FUNCTION_FIELD_CURVES:
        places = [(f, len(f) - 1) for f in monic_irreducibles(E.p, order)] + [(None, 1)]
        rows = ", ".join(f"({d}, {kinds[E.reduction_type(f)]}, {E.trace_at(f)})" for f, d in places)
        out.append(f"  ({E.p}, {order}, [{rows}]),")
    out[-1] = out[-1].rstrip(",")
    out.append("]")
    return out


def brandt_eigenvector_block() -> list[str]:
    L = SupersingularLocus.of(37)
    v = L.common_eigenvector({2: -2, 3: -3, 5: -2, 7: -1})
    ints = [int(x) for x in v]
    return ["/-- A joint eigenvector of B(2), B(3), B(5), B(7) at p = 37 with eigenvalues (-2, -3, -2, -1): the form 37a. -/",
            f"def brandt37Eigenvector : List Int := {lean_list(ints)}"]


def render() -> str:
    lines = ["-- GENERATED by tools/export_lean_data.py; do not edit.", "import LanglandsOracles.Matrix", "", "namespace Oracles", ""]
    lines += brandt_block() + [""] + brandt_eigenvector_block() + [""] + gl1_block() + [""] + function_field_block() + ["", "end Oracles", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    target = ROOT / "lean" / "LanglandsOracles" / "Data.lean"
    text = render()
    if "--check" in sys.argv:
        sys.exit(0 if target.read_text() == text else 1)
    target.write_text(text)
    print(f"wrote {target}")
